---
apiVersion: v1
kind: Pod
metadata:
  name: pod
spec:
  volumes:
  - name: index
    configMap:
      items:
      - { key: "index.html", path : "index.html" }
      name: pod-html
  containers:
  - name: nginx
    image: nginx:latest
    ports:
    - containerPort: 80
      protocol: TCP
    volumeMounts:
    - name: index
      mountPath: /usr/share/nginx/html
