---
apiVersion: v1
kind: Deployment
metadata:
  name: deploy
  labels:
    exo: simple-deploy
spec:
  replicas: 1
  selector:
    exo: simple-deploy
  template:
    metadata:
      name: nginx
      labels:
        exo: simple-deploy
    spec:
      volumes:
      - configMap:
          name: nginx-config 
        name: nginx-config
      - secret:
          defaultMode: 0400
          secretName: basic-auth
          items:
          - { key: .htpasswd, path: .htpasswd }
        name: basic-auth
      restartPolicy: Never
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
          protocol: TCP
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/conf.d
        - name: basic-auth
          mountPath: /secrets
