---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  template:
    spec:
      volumes:
      - configMap:
          name: nginx-config 
        name: nginx-config
      - secret:
          secretName: basic-auth
          items:
          - { key: ".htpasswd", path: ".htpasswd" }
        name: basic-auth
      containers:
      - name: nginx
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/conf.d
        - name: basic-auth
          mountPath: /secrets
