---
apiVersion: v1
kind: Service
metadata:
  name: php 
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: php
spec:
  replicas: 1
  selector: {}
  template:
    metadata:
      name: php
    spec:
      volumes:
      - configMap:
          name: php-data
        name: data
      containers:
      - name: php-apache
        image: php:7.2-apache
        ports:
        - containerPort: 80
        volumeMounts:
        - name: data
          mountPath: /var/www/html
