---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: php
spec:
  template:
    spec:
      containers:
      - name: php-apache
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m
