---
apiVersion: v1
kind: Pod
metadata:
  name: simple-hpa-test
spec:
  restartPolicy: Never
  containers:
  - name: test
    image: busybox:latest
    command:
    - /bin/sh
    - -c
    - |
      while sleep 0.01; do
        echo "ok"
        wget --spider -S "http://{SERVICE}" 2>&1 | grep "HTTP/" | awk '{print $2}'
      done
    env:
    - name: SERVICE
      value: simple-hpa-php
